config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "flats#index"
  #root to: "pages#home"

  resources :flats do
    resources :bookings, except: :destroy
  end

  resources :bookings, only: :destroy
  get "my_bookings", to: "bookings#my_bookings"

  get "my_flats", to: "flats#my_flats"






  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :flat
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy

  validates :address, presence: true
  validates :description, presence: true
  validates :price_per_day, presence: true
  validates :price_per_day, numericality: { only_integer: true }
  validates :guests_allowed, presence: true
  validates :guests_allowed, numericality: { only_integer: true }
  validates :city, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :flats
  has_many :bookings

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def my_bookings
    @bookings = Booking.where(user_id: current_user.id)
  end

  def new
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new # Needed to instantiate the form_with
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @flat = Flat.find(params[:flat_id])
    @booking.flat = @flat

    if @booking.save
      redirect_to my_bookings_path, notice: "Booking was successful! Enjoy your flat."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to flats_path(@flat), notice: "Booking was successfully cancelled."
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all

    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {flat: flat})
      }
    end

    if params[:query].present?
      @flats = @flats.where("city ILIKE ?", "%#{params[:query]}%")
    end
  end

  def my_flats
    @flats = Flat.where(user_id: current_user.id)
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new # Needed to instantiate the form_with
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user

    if @flat.save
      redirect_to @flat, notice: "Flat was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    if @flat.user == current_user
      @flat.destroy
      redirect_to flats_path, notice: "Flat was successfully removed."
    else
      redirect_to flats_path, alert: "Vous n'êtes pas autorisé à supprimer cet appartement."
    end
  end


  private

  def flat_params
    params.require(:flat).permit(:address, :description, :price_per_day, :guests_allowed, :photo, :city)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/my_bookings.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://static.vecteezy.com/system/resources/previews/002/422/814/large_2x/spacious-kitchen-and-dining-room-interior-design-flat-free-vector.jpg);">
  <div class="container"style="margin-top: -20px;">
    <h1><strong>My bookings</strong><strong></strong></h1>
  </div>
</div>


<div class=" container  mt-4 d-flex justify-content-center">

    <% @bookings.each do |booking| %>
      <div class="border m-3 bg-light text-dark p-2 ">
        <p><strong><%= booking.flat.address %></strong></p>
        <p> Start date: </strong><%= booking.start_date %></p>
        <p>End date: </strong><%= booking.end_date %></p>
        <%= link_to "Delete Booking", booking_path(booking), class: "btn btn-dark m-2", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
       </div>
    <% end %>
</div>

app/views/bookings/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://clipground.com/images/clip-art-kitchen-4.jpg);">
  <div class="container"style="margin-top: -20px;">
    <h1><strong>Create a new booking</strong><strong></strong></h1>
  </div>
</div>


<div class="container d-flex justify-content-center vh-50 mt-4 ">
  <%= simple_form_for [@flat, @booking] do |f| %>
    <div , class="mt-5 " >
      <%= f.input :start_date, html5: true %>
    </div>
    <div class="mt-5 mb-4">
     <%= f.input :end_date, html5: true%>
    </div>
    <%= f.submit "Book this flat!", class: "m-3 btn btn-dark m-2" %>
    <% end %>
</div>

app/views/flats/_info_window.html.erb
<h2><%= flat.description %></h2>
<p><%= flat.address %></p>
<p><%= flat.city %></p>

app/views/flats/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://mir-s3-cdn-cf.behance.net/project_modules/2800_opt_1/3f1c6477563161.5c8ae268d2efb.png);">
  <div class="container"style="margin-top: -20px;">
    <h1><strong>View flats to rent for your perfect holiday!</strong></h1>
  </div>
</div>

<div class="index-container ">
  <div class="grid-list column ">
    <% @flats.each do |flat| %>
      <% if flat.photo.present? %>
       <%= link_to flat_path(flat), style: "text-decoration: none" do %>
        <div class="back_images" style="background-image: url('<%= cl_image_path flat.photo.key %>')">
          <p class="city-name"><%= flat.city %></p>
        </div>
        <% end %>
      <% else %>
        <%= link_to flat_path(flat) do %>
         <div class="back_images" style="background-image: url('<%= image_path "logo.png" %>')">
         </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <div id="map" class="column" style="width: 100%; height: 90vh;" data-controller="map"  data-map-markers-value="<%= @markers.to_json %>"  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/flats/my_flats.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.pinimg.com/originals/23/05/d8/2305d86c1cd243e640ca96131dc5c765.jpg);">
  <div class="container"style="margin-top: -20px;">
    <h1><strong>My flats</strong></h1>
  </div>
</div>


<div class="container ">
  <div class="row justify-content-center ">
    <div class="col-md-4 border p-4 mt-3">
      <h3 class="mb-4" >Here are your flats :</h3>


        <ol class="text" >
          <% @flats.each do |flat| %>
          <div class=" d-flex align-items-start ">
            <li class="mb-3">
            <%# <%= link_to "#{flat.address}, #{flat.city}", flat_path(flat), style: "text-decoration: none", class: "text-dark"%>
            <%= link_to flat_path(flat), style: "text-decoration: none", class: "text-dark" do %>
              <%= flat.address  %>
              <%= ","%>
              <strong> <%= flat.city %> </strong>
            <% end %>
            </li>
          </div>
          <% end %>
        </ol>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://yt3.ggpht.com/36ZAuAwB6IpmaPWt4gCa4Dnlrnr4Xw4CcgYbnmndGp-dinibNt5CP9uREElwcJLN2biHdbTMTA=w2120-fcrop64=1,00000000ffffffff-k-c0xffffffff-no-nd-rj);">
  <div class="container"style="margin-top: -20px;">
    <h1><strong>Time to travel, rent out your flat</strong></h1>
  </div>
</div>

<div class=" border-dark p-2 mx-auto mb-4" style="max-width: 400px; ">
  <p class="text-center fw-bold border border-dark p-3 m-0 bg-light text-dark p-2" > Rent your flat! </p>
</div>

<div class="container d-flex justify-content-center align-items-center vh-50">

  <%= simple_form_for(@flat) do |f| %>

  <div class="mb-3">
     <%= f.input :address, label_html: { class: "form-label required" },
      input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
     %>
  </div>

  <div class="row">

    <div class="col-md-6 mb-3">
       <%= f.input :description, label_html: { class: "form-label required" } %>
    </div>

     <div class="col-md-6 mb-3">
      <%= f.input :city, label_html: { class: "form-label required" } %>
    </div>

  </div>

  <div class="row">
    <div class="col-md-6 mb-3">
      <%= f.input :price_per_day, label_html: { class: "form-label required" }%>
   </div>

     <div class="col-md-6 mb-3">
       <%= f.input :guests_allowed, label_html: { class: "form-label required" } %>
      </div>
  </div>

  <div class="mb-3">
    <%= f.input :photo, as: :file %>
  </div>

  <%= f.submit class:" m-3 btn btn-dark m-2" %>

  <% end %>

</div>

app/views/flats/show.html.erb
<div class="container add-top-margin">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="border p-4 mb-4 card-shadow card mt-5 bg-light text-dark p-2">

        <p class="lead mb-2" style="text-align: left;"><strong class="fw-bold">Flast description : </strong><%= @flat.description %></p>
        <p class="lead mb-2" style="text-align: left;"><strong class="fw-bold">Address : </strong><%= @flat.address %></p>
        <p class="lead mb-2" style="text-align: left;"><strong class="fw-bold">City : </strong><%= @flat.city %></p>
        <p class="lead mb-2" style="text-align: left;"><strong class="fw-bold">Price per day : </strong><%= @flat.price_per_day %></p>
        <p class="lead mb-2" style="text-align: left;"><strong class="fw-bold">Guests allowed : </strong><%= @flat.guests_allowed %></p>
        </div>


      <div>
        <% if @flat.photo.present? %>
          <div class="user_flat_images" style="background-image: url('<%= cl_image_path @flat.photo.key, height: 300, crop: :fill %>')"></div>
        <% end %>
      </div>

      <div class="d-flex justify-content-start">
        <% if current_user == @flat.user %>
          <%= link_to "Delete Flat", flat_path(@flat), class: "m-3 btn btn-dark m-2", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
          <% end %>
          <hr>

          <%= link_to "Book this flat", new_flat_booking_path(@flat), class: "m-3 btn btn-dark m-2" %>
          <%=  link_to "Back to Home", flats_path, class: "m-3 btn btn-dark m-2"%>
          <hr>
      </div>
    </div>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css' rel='stylesheet' />
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>
  <body>
      <div class="page-container">
        <div class="navbar-container">
          <%= render "shared/navbar" %>
        </div>
        <main id="main-content">
           <%= yield %>
        </main>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= render "shared/footer" %>
      </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<!-- FOOTER -->
<div class="container my-5">

  <footer class="bg-dark text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Form -->
    <section class="">
      <form action="">
        <!--Grid row-->
        <div class="row d-flex justify-content-center">
          <!--Grid column-->
          <div class="col-auto">
            <p class="pt-2">
              <strong>Sign up for our newsletter</strong>
            </p>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-5 col-12">
            <!-- Email input -->
            <div class="form-outline form-white mb-4">
              <input type="email" id="form5Example2" class="form-control" />
              <label class="form-label" for="form5Example2">Email address</label>
            </div>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-auto">
            <!-- Submit button -->
            <button type="submit" class="btn btn-outline-light mb-4">
              Subscribe
            </button>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </form>
    </section>
    <!-- Section: Form -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>

</div>
<!-- End of .container -->

app/views/shared/_footer.html.erb
  <div id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center">
      <strong>RBNB.com</strong>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom " style="margin-bottom: 0">
  <div class="container-fluid">
    <%= link_to flats_path, class: "navbar-brand" do %>
      <%= image_tag "https://logopond.com/logos/5d50b7e780862243f64312c7c282e654.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse w-100" id="navbarSupportedContent">
      <div class="row justify-content-center">
        <div class="col-sm-8 w-100">
            <%= form_with url: flats_path, method: :get, class: "d-flex" do %>
                <div class="map-auto-complete" data-controller="address-autocomplete" data-address-autocomplete-api-key-value="<%= ENV["MAPBOX_API_KEY"] %>">
                <%= text_field_tag :query,
                      params[:query],
                      class: "form-control d-none",
                      placeholder: "Enter a city to search in",
                      data: {address_autocomplete_target:"address"}
                  %>
                </div>
              <%= submit_tag "Search", name: "", class: "btn btn-primary" %>
            <% end %>
          </div>
        </div>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item active me-4">
            <%= link_to "Home", flats_path, class: "btn btn-outline-dark m-2 btn-rounded ms-4" %>
          </li>
          <li class="nav-item me-4">
            <%= link_to "Create a flat", new_flat_path, class: "btn btn-outline-dark m-2 btn-rounded ms-4" %>
          </li>
          <li class="nav-item me-4">
            <%= link_to "My flats", my_flats_path, class: "btn btn-outline-dark m-2 btn-rounded ms-4" %>
          </li>
          <li class="nav-item me-4">
          <%= link_to "My bookings", my_bookings_path, class: "btn btn-outline-dark m-2 btn-rounded ms-4" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/krokrob", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", "#", class: "dropdown-item" %>
              <%= link_to "Settings", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>